name: MediaTools Autopilot

on:
  workflow_dispatch:

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert nbformat papermill pydrive2 gdown yt-dlp ffmpeg-python openai-whisper srt numpy pandas

      - name: Convert Notebook to Python
        run: |
          jupyter nbconvert --to script MediaTools_Autopilot.ipynb
          mv MediaTools_Autopilot.txt autopilot_script.py || mv MediaTools_Autopilot.py autopilot_script.py

      - name: Patch script (remove Colab-only code + add imports)
        run: |
          # Remove google.colab imports and drive.mount lines
          sed -i '/google.colab/d' autopilot_script.py
          sed -i '/drive.mount/d' autopilot_script.py
          
          # Ensure "os" and "pydrive2" imports exist
          grep -q '^import os' autopilot_script.py || echo 'import os' >> autopilot_script.py
          grep -q '^from pydrive2.auth import GoogleAuth' autopilot_script.py || echo 'from pydrive2.auth import GoogleAuth' >> autopilot_script.py
          grep -q '^from pydrive2.drive import GoogleDrive' autopilot_script.py || echo 'from pydrive2.drive import GoogleDrive' >> autopilot_script.py

      - name: Run autopilot script
        run: |
          echo "Running autopilot_script.py..."
          python3 autopilot_script.py

      - name: Upload results to Google Drive
        if: always()
        run: |
          python - <<'PY'
          import os, glob, json
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          # Auth
          gauth = GoogleAuth()
          gauth.LoadCredentialsFile("credentials.json")
          if gauth.credentials is None:
              gauth.LocalWebserverAuth()
          elif gauth.access_token_expired:
              gauth.Refresh()
          else:
              gauth.Authorize()
          gauth.SaveCredentialsFile("credentials.json")

          drive = GoogleDrive(gauth)

          folder_id = "1hyZKoX2dZW0VqtYiSWw4vhp4loJo-H0z"  # your Drive folder ID
          for file in glob.glob("Autopost_Clips/*"):
              f = drive.CreateFile({"parents": [{"id": folder_id}]})
              f.SetContentFile(file)
              f.Upload()
              print("✅ Uploaded:", file)
          PY
