name: MediaTools Autopilot

on:
  workflow_dispatch:

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install papermill
          pip install pydrive2
          pip install gdown
          pip install yt-dlp
          pip install ffmpeg-python
          pip install openai-whisper
          pip install srt
          pip install numpy
          pip install pandas

      - name: Convert Notebook to Python
        run: |
          jupyter nbconvert --to python MediaTools_Autopilot.ipynb --output autopilot_script.py || true

      - name: Normalize script filename
        run: |
          if [ -f autopilot_script.txt ]; then mv autopilot_script.txt autopilot_script.py; fi

      - name: Patch script (remove Colab-only code + add imports)
        run: |
          sed -i '/google.colab/d' autopilot_script.py || true
          sed -i '/get_ipython/d' autopilot_script.py || true
          sed -i '1i import os' autopilot_script.py

      - name: Run autopilot script
        run: |
          echo "Running autopilot_script.py..."
          python3 autopilot_script.py || true

      - name: Upload results to Google Drive
        if: always()
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
        run: |
          python - <<'PY'
          import os, glob
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          # Save service account JSON from secret
          creds_path = "service_account.json"
          with open(creds_path, "w") as f:
              f.write(os.environ["GDRIVE_KEY"])

          gauth = GoogleAuth()
          gauth.settings['service_config'] = {'client_json_file_path': creds_path}
          gauth.ServiceAuth()
          drive = GoogleDrive(gauth)

          folder_id = os.environ["FOLDER_ID"]
          for file in glob.glob("Autopost_Clips/*"):
              f = drive.CreateFile({"parents": [{"id": folder_id}]})
              f.SetContentFile(file)
              f.Upload()
              print("✅ Uploaded:", file)
          PY

      - name: Upload artifacts (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autopost_results
          path: Autopost_Clips/*
