name: MediaTools Autopilot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas ffmpeg-python yt-dlp openai-whisper srt pydrive2 nbconvert

      - name: Convert Notebook to Python
        run: |
          jupyter nbconvert --to script MediaTools_Autopilot.ipynb --output autopilot_script.py

      - name: Patch autopilot script (remove Colab-only + import os)
        run: |
          sed -i '/google.colab/d' autopilot_script.py
          sed -i '1i import os' autopilot_script.py

      - name: Run autopilot script
        run: |
          echo "Running autopilot_script.py..."
          python3 autopilot_script.py

      - name: Upload results to Google Drive
        env:
          GDRIVE_FOLDER_ID: 1hyZKoX2dZW0VqtYiSWw4vhp4loJo-H0z
        run: |
          python3 <<'PY'
          import os
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          gauth = GoogleAuth()
          gauth.LoadCredentialsFile("creds.json")
          if not gauth.credentials:
              gauth.LocalWebserverAuth()
          drive = GoogleDrive(gauth)

          folder_id = os.environ["GDRIVE_FOLDER_ID"]
          out_dir = "Autopost_Clips"

          for root, _, files in os.walk(out_dir):
              for file in files:
                  path = os.path.join(root, file)
                  f = drive.CreateFile({"title": file, "parents": [{"id": folder_id}]})
                  f.SetContentFile(path)
                  f.Upload()
                  print("✅ Uploaded", file)
          PY

      - name: Upload artifacts (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autopilot-results
          path: ./Autopost_Clips/**
