name: MediaTools Autopilot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert pandas ffmpeg-python yt-dlp openai-whisper srt pydrive2

      - name: Convert Notebook to script
        run: |
          jupyter nbconvert --to script MediaTools_Autopilot.ipynb --output autopilot_script

      - name: Run autopilot script
        run: |
          python3 autopilot_script.py
        env:
          GDRIVE_FOLDER_ID: "YOUR_DRIVE_FOLDER_ID"   # 🔹 Replace this with your actual Drive folder ID
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GDRIVE_KEY }}

      - name: Upload results to Google Drive
        if: always()
        run: |
          python3 - <<'PY'
          import os, glob
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          gauth = GoogleAuth()
          gauth.LoadCredentialsFile("service_account.json")
          drive = GoogleDrive(gauth)

          folder_id = os.environ.get("GDRIVE_FOLDER_ID", "")

          for fp in glob.glob("./Autopost_Clips/*"):
              fname = os.path.basename(fp)
              f = drive.CreateFile({"title": fname, "parents": [{"id": folder_id}]})
              f.SetContentFile(fp)
              f.Upload()
              print(f"✅ Uploaded {fname} to Google Drive")
          PY

      - name: Upload artifacts (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autopilot-results
          path: ./Autopost_Clips/**
