name: MediaTools Autopilot

on:
  workflow_dispatch:

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert gdown pydrive2

      - name: Convert Notebook to Python (force name)
        run: |
          jupyter nbconvert --to script MediaTools_Autopilot.ipynb --output autopilot_script

      - name: Run autopilot script
        run: |
          echo "Running autopilot_script.py..."
          ls -lh
          python3 autopilot_script.py

      - name: Upload results to Google Drive
        env:
          GDRIVE_FOLDER_ID: 1hyZKoX2dZW0VqtYiSWw4vhp4loJo-H0z
          SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_JSON }}
        run: |
          python3 - <<'PY'
          import os, json
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          creds_path = "gdrive_key.json"
          with open(creds_path, "w") as f:
              f.write(os.environ["SERVICE_ACCOUNT_JSON"])

          gauth = GoogleAuth()
          gauth.LoadCredentialsFile(creds_path)
          drive = GoogleDrive(gauth)

          folder_id = os.environ["GDRIVE_FOLDER_ID"]

          for root, _, files in os.walk("Autopost_Clips"):
              for name in files:
                  filepath = os.path.join(root, name)
                  f = drive.CreateFile({
                      "title": name,
                      "parents": [{"id": folder_id}]
                  })
                  f.SetContentFile(filepath)
                  f.Upload()
                  print("✅ Uploaded:", name)
          PY
