name: MediaTools Autopilot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours

jobs:
  run-autopilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill pyyaml pandas ffmpeg-python yt-dlp openai-whisper srt pydrive2

      - name: Run Notebook with Papermill
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          papermill MediaTools_Autopilot.ipynb executed_${TIMESTAMP}.ipynb

      - name: Upload results to Google Drive
        env:
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: |
          echo "$GDRIVE_KEY" > sa.json

          python - <<'EOF'
          import os, glob, json, datetime
          from pydrive2.auth import GoogleAuth
          from pydrive2.drive import GoogleDrive

          # Authenticate
          with open("sa.json","w") as f: f.write(os.getenv("GDRIVE_KEY"))
          gauth = GoogleAuth()
          gauth.LoadCredentialsFile("sa.json")
          drive = GoogleDrive(gauth)

          folder_id = os.getenv("FOLDER_ID")
          ts = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

          # Upload all generated files (mp4 + txt)
          for file in glob.glob("**/*", recursive=True):
              if file.endswith((".mp4",".txt",".ipynb")):
                  new_name = f"{os.path.basename(file).split('.')[0]}_{ts}{os.path.splitext(file)[1]}"
                  gfile = drive.CreateFile({"title": new_name, "parents": [{"id": folder_id}]})
                  gfile.SetContentFile(file)
                  gfile.Upload()
                  print("✔ Uploaded:", new_name)
          EOF
